name: Build by  fireworld & Test
on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Build project
      env:
          LOOP_KEY_ALIAS: ${{ secrets.LOOP_KEY_ALIAS }}
          LOOP_KEY_PASSWORD: ${{ secrets.LOOP_KEY_PASSWORD }}
          LOOP_STORE_PASSWORD: ${{ secrets.LOOP_STORE_PASSWORD }}
          LOOP_KEY_STORE: ${{ github.workspace }}/key.jks
          
      run: |
        VERSION=$(grep versionName uhabits-android/build.gradle.kts | sed -e 's/.*"\([^"]*\)".*/\1/g')
        echo ${{ secrets.LOOP_SIGNKEY }} | base64 --decode > ${{ github.workspace }}/key.jks
        ./gradlew uhabits-android:assembleRelease
        cp -v \
            uhabits-android/build/outputs/apk/release/uhabits-android-release.apk \
            uhabits-android/build/loop-"$VERSION"-release.apk

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          uhabits-android/build
